### ISSUE TITLE
mesonconf executable is deprecated

### ISSUE THREAD

**Issue by GabMus** [GabMus/razerCommander#47]
use `meson configure` instead (change the readme and arch pkgbuild)

**Comment by GabMus** [comment]
works like this `meson configure -Dprefix=$(pwd)/testdir`

**Comment by nicolasCossio** [comment]
Hello, I have a problem when im trying to build the razerCommander
Im following this steps but when reach to: 

 `~/razerCommander/builddir $  meson configure -Dprefix=$(pwd)/testdir `

I got this error:
```
Error during basic setup:

Neither directory contains a build file meson.build
```
I did this:
`~/razerCommander $ meson configure -Dprefix=$(pwd)/testdir`
(because the build file meson.build is in razerCommander) and it worked but when tried 
`~/razerCommander/builddir $ ninja install` 
(beacause the build file build.ninja is in builddir) 

I got this:
```
[1/2] Installing files.
Installing subdir /home/nicolas/razerCommander/razercommander to /usr/local/lib/python3.5/site-packages
Traceback (most recent call last):
  File "/usr/share/meson/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/share/meson/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 260, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 248, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 306, in run
    do_install(datafilename)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 124, in do_install
    install_subdirs(d) # Must be first, because it needs to delete the old subtree.
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 139, in install_subdirs
    os.makedirs(dst_dir)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/site-packages'
FAILED: install 
'/usr/bin/python3' '/usr/share/meson/meson' '--internal' 'install' '/home/nicolas/razerCommander/builddir/meson-private/install.dat'
ninja: build stopped: subcommand failed.
```
I really dont know what to do, I wish you could help me @GabMus .
