### ISSUE TITLE
Error when trying to use razerCommander

### ISSUE THREAD

**Issue by carlosg-gh** [GabMus/razerCommander#7]
Installed from the AUR. The razer-driver was installed manually and tested.

```
kuro@Horus:/sys/bus/hid/drivers/razerkbd|
⇒  pacaur -Qi razer-driver-dkms 
Name            : razer-driver-dkms
Version         : 1.0.0-2
Description     : An entirely open source driver for managing Razer peripherals on Linux. (DKMS)
Architecture    : x86_64
URL             : https://github.com/terrycain/razer_drivers
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : dkms  udev
Optional Deps   : None
Required By     : razer-daemon
Optional For    : None
Conflicts With  : razer-driver
Replaces        : None
Installed Size  : 187.00 KiB
Packager        : Unknown Packager
Build Date      : Thu 25 Aug 2016 04:40:18 PM CEST
Install Date    : Thu 25 Aug 2016 04:41:04 PM CEST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

kuro@Horus:/sys/bus/hid/drivers/razerkbd|
⇒  pacaur -Qi razer-daemon     
Name            : razer-daemon
Version         : 1.0.0-2
Description     : A daemon for controlling razer-driver
Architecture    : any
URL             : https://github.com/terrycain/razer_drivers
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : razer-driver-dkms  python  python-dbus  python-gobject  python-setproctitle  xautomation  xdotool  libdbus
Optional Deps   : python-razer: python library for controlling the daemon [installed]
Required By     : python-razer
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 188.00 KiB
Packager        : Unknown Packager
Build Date      : Thu 25 Aug 2016 04:41:53 PM CEST
Install Date    : Thu 25 Aug 2016 04:42:01 PM CEST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

kuro@Horus:/sys/bus/hid/drivers/razerkbd|
⇒  pacaur -Qi razercommander-git 
Name            : razercommander-git
Version         : 0.4-4
Description     : A simple GTK control center for managing razer peripherals on Linux. Make sure to install https://github.com/terrycain/razer_drivers first.
Architecture    : x86_64
URL             : https://github.com/gabmus/razercommander
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : gtk3>=3.20,python
Optional Deps   : None
Required By     : None
Optional For    : python-razer
Conflicts With  : None
Replaces        : None
Installed Size  : 951.00 KiB
Packager        : Unknown Packager
Build Date      : Thu 25 Aug 2016 04:54:16 PM CEST
Install Date    : Thu 25 Aug 2016 04:54:16 PM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

```

This is the output of both razercommander and python /route/to/main.py:

```
** (main.py:25443): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.razer': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/razer/client/__init__.py", line 15, in __init__
    self._dbus = session_bus.get_object("org.razer", "/org/razer")
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.5/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.razer was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 7, in <module>
    import device
  File "/usr/share/razercommander/device.py", line 10, in <module>
    device_manager = rclient.DeviceManager()
  File "/usr/lib/python3.5/site-packages/razer/client/__init__.py", line 17, in __init__
    raise DaemonNotFound("Could not connect to daemon")
razer.client.DaemonNotFound: Could not connect to daemon

```

**Comment by GabMus** [comment]
Apparently the daemon isn't running, try running `razer-service` on your
terminal and try again

**Comment by GabMus** [comment]
And I just noticed you said that you installed the driver "manually". Do you mean using make? If so, try installing using the provided PKGBUILDs in terrycain's repo

**Comment by kusayuzayushko** [comment]
Same problem here. razer-driver-dkms, razer-daemon and python-razer installed using provided PKGBUILDs. 
razercommander faild with

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.razer': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/razer/client/__init__.py", line 15, in __init__
    self._dbus = session_bus.get_object("org.razer", "/org/razer")
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.5/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.razer was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 7, in <module>
    import device
  File "/usr/share/razercommander/device.py", line 10, in <module>
    device_manager = rclient.DeviceManager()
  File "/usr/lib/python3.5/site-packages/razer/client/__init__.py", line 17, in __init__
    raise DaemonNotFound("Could not connect to daemon")
razer.client.DaemonNotFound: Could not connect to daemon
```

razer-service faled with

```
Traceback (most recent call last):
  File "/usr/bin/razer-service", line 6, in <module>
    from razer_daemon.daemon import daemonize
  File "/usr/lib/python3.5/site-packages/razer_daemon/daemon.py", line 23, in <module>
    import razer_daemon.hardware
  File "/usr/lib/python3.5/site-packages/razer_daemon/hardware/__init__.py", line 7, in <module>
    from razer_daemon.hardware.mouse import RazerMambaChromaWireless
  File "/usr/lib/python3.5/site-packages/razer_daemon/hardware/mouse.py", line 5, in <module>
    from razer_daemon.misc.battery_notifier import BatteryManager
  File "/usr/lib/python3.5/site-packages/razer_daemon/misc/battery_notifier.py", line 8, in <module>
    import notify2
ImportError: No module named 'notify2'
```

Iven thought that's not your problem, i'm just going to let this here.

**Comment by GabMus** [comment]
EASY PEASY: just install `python-notify2` from AUR

**Comment by ghost** [comment]
Not sure about AUR but on Ubuntu you have to install `python3-notify2`, which is a separate package to `python-notify2`.

**Comment by GabMus** [comment]
In arch packaging python is python3 and python2 is python2, so the right
package to install is python-notify2 from AUR

**Comment by GabMus** [comment]
@kusayuzayushko please report back and tell me if your issue is fixed so I can close it

**Comment by GabMus** [comment]
Closing for now, assuming it's solves. If it's not, reopen it
