### ISSUE TITLE
Custom Mode does not apply on Razer Blade Stealth Late 2016

### ISSUE THREAD

**Issue by Bl4d3s** [GabMus/razerCommander#71]
Hello, 
all other modes work, but if I want to apply a custom layout it does nothing. It still shows the previous selected mode. Any tips ?

Edit: These errors I get when building locally:
`[michael@Blade builddir]$ ninja run
[0/1] Running external command run.
Importing device logic, waiting for daemon
Device logic loaded, daemon is alive
Traceback (most recent call last):
  File "/home/michael/razercommander/razercommander/__main__.py", line 794, in on_universalApplyButton_clicked
    self.enableFXwSettings(currentFX)
  File "/home/michael/razercommander/razercommander/__main__.py", line 544, in enableFXwSettings
    self.active_razer_device.applyCustom(self.rkb)
  File "/home/michael/razercommander/razercommander/device.py", line 447, in applyCustom
    rindex, cindex, self._make_color_tuple(key.color)
  File "/usr/lib/python3.6/site-packages/openrazer/client/fx.py", line 1000, in set
    self.__setitem__((y, x), rgb)
  File "/usr/lib/python3.6/site-packages/openrazer/client/fx.py", line 961, in __setitem__
    assert 0 <= key[1] < self._cols, "Column out of bounds"
AssertionError: Column out of bounds
`

Edit2: I looked a bit into your code. I think I need to define a correct Layout for my laptop. Ill try to do this and report back.

**Comment by barabanus** [comment]
I had the same issue with Razer Blade 15 (2018), so I patched keyboard layout within `kblayouts.py`:
```
'ansi_us': [
  [INV_GHOST, "esc", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "ins", "del",],
  [INV_GHOST, "`", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", INV_GHOST, "⟸",],
  [INV_GHOST, "tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", INV_GHOST, "\\",],
  [INV_GHOST, "caps", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "\'", INV_GHOST, INV_GHOST, "enter",],
  [INV_GHOST, "shift", INV_GHOST, "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "↑", GHOST, "shift",],
  [INV_GHOST, "ctrl", "fn", "⊞", INV_GHOST, "alt", INV_GHOST, "spacebar", INV_GHOST, "alt", INV_GHOST, "ctrl", "←", "↓", "→", "fn",]
]
```
